print("MutsFM Elevator Inc.")
print("Cart Dispense Software")
print("Loading Software...")
sleep(1)
print("Load Complete")
print("Powering Track...")
redstone.setOutput("back", true)
sleep(1)
print("Tracks Powered")
print("Establishing Network Connection...")
rednet.open("top")
sleep(1)
if rednet.isOpen() then print("Connection Established!") end
print("Starting Cart Dispensing Programme")
shell.run("cartdispenser")
